import {existsSync, writeFileSync} from "node:fs";
import type {AsPlainObject} from "minisearch";

const HTTP_ROOT = "http://127.0.0.1:3033";

const categories = ["map", "plot", "cool"];

async function main() {
  const ms: AsPlainObject = await fetch(`${HTTP_ROOT}/_observablehq/minisearch.json`).then((resp) => resp.json());
  const documents: {id: string; title: string; light?: string; dark?: string}[] = [];

  const cat = new Map<string, Set<string>>();
  for (const [word, fields] of Object.values(ms.index)) {
    if (categories.includes(word)) {
      // word is in title[0] or keywords[2]
      cat.set(word, new Set([...(Object.keys(fields[0] ?? {}) ?? []), ...(Object.keys(fields[2] ?? {}) ?? [])]));
    }
  }

  for (const [i, id] of Object.entries(ms.documentIds)) {
    const pathLight = `thumbnail${id}-light.png`;
    const pathDark = `thumbnail${id}-dark.png`;
    let hasLight = false;
    let hasDark = false;
    try {
      if (existsSync(`src/${pathLight}`)) hasLight = true;
      if (existsSync(`src/${pathDark}`)) hasDark = true;
    } catch (e) {}
    documents.push({
      id: id as string,
      title: ms.storedFields[i].title,
      light: hasLight ? pathLight : undefined,
      dark: hasDark ? pathDark : undefined
    });
  }

  cat.set("more…", new Set(Array.from(documents, (_, i) => `${i}`)));
  const seen = new Set();

  const groups = Array.from(
    cat,
    ([word, ids]) =>
      `## ${word}\n\n<div class="list">\n${Array.from(ids, (id) =>
        seen.has(id) ? null : (seen.add(id), documents[id])
      )
        .filter((d) => d != null)
        .map(({id, title, light, dark}) =>
          light && dark
            ? `<a href="..${id}"><picture><source srcset="../${dark}" media="(prefers-color-scheme: dark)"><img src="../${light}" loading="lazy"></picture><q>${title}</q></a>`
            : light || dark
            ? `<a href="..${id}"><img src="../${light ?? dark}" loading="lazy"><q>${title}</q></a>`
            : `<a href="..${id}"><q>${title}</q></a>`
        )
        .join("\n")}\n</div>`
  );

  const HEAD = `---
theme: dashboard
title: Gallery
index: false
sidebar: false
comment: Page generated by generate-index.ts
---

<style>
.list {
  margin-top: 2em;
  display: flex;
  flex-wrap: wrap;
  max-width: 100%;
  gap: 10px;
}
.list a {
  display: block;
  position: relative;
  max-width: 320px;
  width: 260px;
  flex-grow: 1;
  height: 195px;
  border: 2px solid var(--theme-foreground-focus);
  font-family: var(--sans-serif);
}
.list a:hover {
  box-shadow: 0 4px 12px var(--theme-foreground-focus);
  transform: translateY(-1px);
}
.list a q {
  position: absolute;
  top: 0;
  left: 0;
  quotes: none;
  padding: 4px 15px;
  background: var(--theme-foreground-focus);
  color: var(--theme-background-alt);
  max-width: 60%;
  border-radius: 0 0 14px;
  line-height: 1.25em;
  max-height: 2.5em;
  overflow: hidden;
  text-overflow: ellipsis;
}
.list a img {
  width: 100%;
  height: 100%;
  object-fit: cover;
}
h2 {
  margin-top: 3em;
}
</style>`;

  writeFileSync(
    "src/thumbnail/index.md",
    `${HEAD}\n\n${groups.join(`\n\n\n`)}
`
  );
}

main();
