import * as d3 from "npm:d3-geo";
import * as d3P from "npm:d3-geo-projection";

export const projections = [
  {name: "Airy’s minimum error", value: d3P.geoAiry},
  {name: "Aitoff", value: d3P.geoAitoff},
  {name: "American polyconic", value: d3P.geoPolyconic},
  {name: "armadillo", value: d3P.geoArmadillo},
  {name: "August", value: d3P.geoAugust},
  {name: "azimuthal equal-area", value: d3.geoAzimuthalEqualArea},
  {name: "azimuthal equidistant", value: d3.geoAzimuthalEquidistant},
  {name: "Baker dinomic", value: d3P.geoBaker},
  {name: "Berghaus’ star", value: d3P.geoBerghaus},
  {name: "Bertin’s 1953", value: d3P.geoBertin1953},
  {name: "Boggs’ eumorphic", value: d3P.geoBoggs},
  {name: "Boggs’ eumorphic (interrupted)", value: d3P.geoInterruptedBoggs},
  {name: "Bonne", value: d3P.geoBonne},
  {name: "Bottomley", value: d3P.geoBottomley},
  {name: "Bromley", value: d3P.geoBromley},
  {name: "Butterfly (gnomonic)", value: d3P.geoPolyhedralButterfly},
  {name: "Butterfly (Collignon)", value: d3P.geoPolyhedralCollignon},
  {name: "Butterfly (Waterman)", value: d3P.geoPolyhedralWaterman},
  {name: "Collignon", value: d3P.geoCollignon},
  // {name: "conic conformal", value: d3.geoConicConformal}, // Not suitable for world maps.
  {name: "conic equal-area", value: d3.geoConicEqualArea},
  {name: "conic equidistant", value: d3.geoConicEquidistant},
  {name: "Craig retroazimuthal", value: d3P.geoCraig},
  {name: "Craster parabolic", value: d3P.geoCraster},
  {name: "cylindrical equal-area", value: d3P.geoCylindricalEqualArea},
  {name: "cylindrical stereographic", value: d3P.geoCylindricalStereographic},
  {name: "Eckert I", value: d3P.geoEckert1},
  {name: "Eckert II", value: d3P.geoEckert2},
  {name: "Eckert III", value: d3P.geoEckert3},
  {name: "Eckert IV", value: d3P.geoEckert4},
  {name: "Eckert V", value: d3P.geoEckert5},
  {name: "Eckert VI", value: d3P.geoEckert6},
  {name: "Eisenlohr conformal", value: d3P.geoEisenlohr},
  {name: "Equal Earth", value: d3.geoEqualEarth},
  {name: "Equirectangular (plate carrée)", value: d3.geoEquirectangular},
  {name: "Fahey pseudocylindrical", value: d3P.geoFahey},
  {name: "flat-polar parabolic", value: d3P.geoMtFlatPolarParabolic},
  {name: "flat-polar quartic", value: d3P.geoMtFlatPolarQuartic},
  {name: "flat-polar sinusoidal", value: d3P.geoMtFlatPolarSinusoidal},
  {name: "Foucaut’s stereographic equivalent", value: d3P.geoFoucaut},
  {name: "Foucaut’s sinusoidal", value: d3P.geoFoucautSinusoidal},
  {name: "general perspective", value: d3P.geoSatellite},
  {name: "Gilbert’s two-world", value: d3P.geoGilbert},
  {name: "Gingery", value: d3P.geoGingery},
  {name: "Ginzburg V", value: d3P.geoGinzburg5},
  {name: "Ginzburg VI", value: d3P.geoGinzburg6},
  {name: "Ginzburg VIII", value: d3P.geoGinzburg8},
  {name: "Ginzburg IX", value: d3P.geoGinzburg9},
  {name: "Goode’s homolosine", value: d3P.geoHomolosine},
  {name: "Goode’s homolosine (interrupted)", value: d3P.geoInterruptedHomolosine},
  {name: "gnomonic", value: d3.geoGnomonic},
  {name: "Gringorten square", value: d3P.geoGringorten},
  {name: "Gringorten quincuncial", value: d3P.geoGringortenQuincuncial},
  {name: "Guyou square", value: d3P.geoGuyou},
  {name: "Hammer", value: d3P.geoHammer},
  {name: "Hammer retroazimuthal", value: d3P.geoHammerRetroazimuthal},
  {name: "HEALPix", value: d3P.geoHealpix},
  {name: "Hill eucyclic", value: d3P.geoHill},
  {name: "Hufnagel pseudocylindrical", value: d3P.geoHufnagel},
  {name: "Kavrayskiy VII", value: d3P.geoKavrayskiy7},
  {name: "Lagrange conformal", value: d3P.geoLagrange},
  {name: "Larrivée", value: d3P.geoLarrivee},
  {name: "Laskowski tri-optimal", value: d3P.geoLaskowski},
  // {name: "Littrow retroazimuthal", value: d3P.geoLittrow}, // Not suitable for world maps.
  {name: "Loximuthal", value: d3P.geoLoximuthal},
  {name: "Mercator", value: d3.geoMercator},
  {name: "Miller cylindrical", value: d3P.geoMiller},
  {name: "Mollweide", value: d3P.geoMollweide},
  {name: "Mollweide (Goode’s interrupted)", value: d3P.geoInterruptedMollweide},
  {name: "Mollweide (interrupted hemispheres)", value: d3P.geoInterruptedMollweideHemispheres},
  {name: "Natural Earth", value: d3.geoNaturalEarth1},
  {name: "Natural Earth II", value: d3P.geoNaturalEarth2},
  {name: "Nell–Hammer", value: d3P.geoNellHammer},
  {name: "Nicolosi globular", value: d3P.geoNicolosi},
  {name: "orthographic", value: d3.geoOrthographic},
  {name: "Patterson cylindrical", value: d3P.geoPatterson},
  {name: "Peirce quincuncial", value: d3P.geoPeirceQuincuncial},
  {name: "rectangular polyconic", value: d3P.geoRectangularPolyconic},
  {name: "Robinson", value: d3P.geoRobinson},
  {name: "sinusoidal", value: d3P.geoSinusoidal},
  {name: "sinusoidal (interrupted)", value: d3P.geoInterruptedSinusoidal},
  {name: "sinu-Mollweide", value: d3P.geoSinuMollweide},
  {name: "sinu-Mollweide (interrupted)", value: d3P.geoInterruptedSinuMollweide},
  {name: "stereographic", value: d3.geoStereographic},
  {name: "Times", value: d3P.geoTimes},
  {name: "Tobler hyperelliptical", value: d3P.geoHyperelliptical},
  {name: "transverse Mercator", value: d3.geoTransverseMercator},
  {name: "Van der Grinten", value: d3P.geoVanDerGrinten},
  {name: "Van der Grinten II", value: d3P.geoVanDerGrinten2},
  {name: "Van der Grinten III", value: d3P.geoVanDerGrinten3},
  {name: "Van der Grinten IV", value: d3P.geoVanDerGrinten4},
  {name: "Wagner IV", value: d3P.geoWagner4},
  {name: "Wagner VI", value: d3P.geoWagner6},
  {name: "Wagner VII", value: d3P.geoWagner7},
  {name: "Werner", value: () => d3P.geoBonne().parallel(90)},
  {name: "Wiechel", value: d3P.geoWiechel},
  {name: "Winkel tripel", value: d3P.geoWinkel3}
];
